#!/bin/tcsh -ef 
setenv INSTANCE metaarchive
setenv PLUGINS https://svn.library.emory.edu/oss/metasource/branches/release/plugins/xml

# URL OF companion PHP database (remeber to trasnport the up to date data there) 
setenv PHP_URL http://www.metaarchive.org/tools/conspectus_v1/php_prod

if (0) then 
rake db:redo
rake conspectus:update

# get plugins (if there are new ones) 
if (-e  config/data/$INSTANCE/plugins) then 
   svn up config/data/$INSTANCE/plugins
else 
   (cd config/data/$INSTANCE; svn co $PLUGINS plugins) 
endif 
rake lockss:import_plugins CHOPDIR=4 PLUGINS=config/data/$INSTANCE/plugins 
rake plugin:cleanup_base_url_params 
endif

# Hook up php metadata 
rake archive:config_ma_editor \
            CREATE=$PHP_URL/create.php \
            UPDATE=$PHP_URL'/edit.php?coll_id=<ID>&title=<TITLE>' \
            SHOW=$PHP_URL'/view.php?coll_id=<ID>&title=<TITLE>' \
	    NAME=SDC 
rake archive:config_ma_editor \
            CREATE=$PHP_URL/create.php \
            UPDATE=$PHP_URL'/edit.php?coll_id=<ID>&title=<TITLE>' \
            SHOW=$PHP_URL'/view.php?coll_id=<ID>&title=<TITLE>' \
	    NAME=ETD 
exit 0; 

echo "** Getting Data from php conspectus "
wget -O /dev/null   $PHP_URL/cleanup.php
wget -O collids.csv $PHP_URL/gen_id_list.php
wget -O lockss.xml 	$PHP_URL/gen_lockssxml.php
echo "id,plugin_name,base_url,title,description" > collids_no_theses.csv 
fgrep -v theses collids.csv >> collids_no_theses.csv 
echo "id,plugin_name,base_url,title,description" > collids_theses.csv 
fgrep theses collids.csv >> collids_theses.csv 
rake collection:csv_get FILE=collids_no_theses.csv CREATE=true CREATE_PLUGIN=true ARCHIVE=SDC
rake collection:csv_get FILE=collids_theses.csv CREATE=true CREATE_PLUGIN=true ARCHIVE=ETD
rake lockss:import_content_defs ARCHIVE=SDC DO_COLLS=false DO_AUS=true AU_STATE=preserved N_PROP_LEVEL=1 FILE=lockss.xml

rake db:info
