#!/bin/tcsh -f 
source ~/.metaarchive.rc 
mkdir -p $DATE 

if (0) then 
# get au status table 
pullTable -u $MACACHE_USER -p $MACACHE_PWD -server `cachedns test` -table AU_Status -O - | fgrep 'Folger Images 2nd Batch' > $DATE/Status
fgrep -v "AuLastCrawl=-1" $DATE/Status | awk '{FS=","; OFS="\t"; print $5, $6, $8, $11, $1}' | sed 's/DiskUsage=//' | sort -r -n > $DATE/Status.sizes
fgrep  "AuLastCrawl=-1" $DATE/Status | awk '{FS=","; OFS="\t"; print $1}' > $DATE/Status.crawling
echo ">>> Sizes  " 
cat $DATE/Status.sizes
echo  ">>> Crawling " `wc -l $DATE/Status.crawling` 
endif

if (0) then 
# get crawl status  table 
pullTable -u $MACACHE_USER -p $MACACHE_PWD -server `cachedns test` -table CrawlStatus -O - | fgrep 'Folger Images 2nd Batch' > $DATE/CrawlStatus
endif 
awk '/num_urls_with_errors=0/  { FS=","; OFS="\t";  print $6, $7, $8, $10, $11, $14, $9 }' $DATE/CrawlStatus | sed 's/au=/AuName=/' > $DATE/CrawlStatus.noerrors 

#echo ">>> Sizes  " 
#cat $DATE/Status.sizes
echo  ">>> Crawling " `wc -l $DATE/Status.crawling` 

