#!/usr/bin/perl  

use Getopt::Long; 
$DIR;

if (0 == parseargs()) {
    doit(); 
    exit(0); 
}
exit(1) ;

sub parseargs 
{
 
 if ($ARGV[0]) { 
    $DIR = $ARGV[0]; 
 } else {
    usage(); 
    return 1; 
 }
 return 0; 
}
 
sub usage 
{
print "usage: rm_respo REPOS\n"; 
print "\tdo rm -rf /caches/cache/REPOS \n"; 
}

sub doit
{
   systm("/bin/rm -rf /caches/cache/$DIR"); 
}

sub systm
{
   my($cmd) = (@_); 
   my($rc) = system($cmd); 
   trace($cmd); 
   if ($rc != 0) {
       print STDERR "FAILED: $cmd\n"; 
   } 
}

sub trace
{
   my $str = join(' ', @_); 
   print $str . "\n"; 
}

