#!/bin/tcsh 
#set echo 
set fullname  =   $1; 
set dir  =  $fullname:h; 
set from = `head -1 $fullname`;  set from = $from:r;  set from = `echo $from | sed s/^0//;  `
set to = `tail -1 $fullname`;  set to = $to:r;  set to = `echo $to | sed s/^0//; `  

set manifest = "$dir/manifest-$from-$to.html"; 
echo $manifest; 

cat header.html > $manifest; 
foreach f (`cat $fullname`) 
    echo "\t<li> <a href='./$f'> $f </a> $f </li>" >> $manifest
end 
cat footer.html >> $manifest
