#!/bin/tcsh 
echo -n "metaarchive password: :"
set p = $1
echo "DROP DATABASE lockssview;" | mysql --user=metaarchive --password=$1
echo "CREATE DATABASE lockssview;" | mysql --user=metaarchive --password=$1
manage.py syncdb



