#!/bin/tcsh -f 
set base_url='http://conspectus.dev.metaarchive.org';
set base_url='http://localhost:3000';
#set echo 

echo "\n>>>> ROOT ";
wget -S -O /dev/null $base_url  >& stderr
echo -n $base_url; fgrep HTTP stderr | fgrep -v awaiting

echo "\n>>>> ALL ";
echo ">> EXPECT OK";
foreach cls ( "archives" "content_providers" "plugins" "collections")
   foreach f (  \
      $base_url/$cls \
      $base_url/$cls/1 \
      $base_url/$cls.xml \
   )
      wget -S -O /dev/null $f  >& stderr
      echo -n $f; fgrep HTTP stderr | fgrep -v awaiting
   end
end
foreach cls ( "content_providers" "collections")
      set f = "$base_url/$cls/1.xml";
      wget -S -O /dev/null $f  >& stderr
      echo -n $f; fgrep HTTP stderr | fgrep -v awaiting
end 

echo ">> EXPECT Moved -> OK  ";
foreach cls ( "archives" "plugins" "content_providers" "collections" )
      set f = "$base_url/$cls/find/none/show" 
      wget -S -O /dev/null $f  >& stderr
      echo -n $f; fgrep HTTP stderr | fgrep -v awaiting
end 

echo ">> EXPECT WHATEVER  ";
foreach cls ( "archives" "plugins" )
      set f = "$base_url/$cls/1.xml";
      wget -S -O /dev/null $f  >& stderr
      echo -n $f; fgrep HTTP stderr | fgrep -v awaiting
end 

echo ">> EXPECT ERROR";
foreach cls ("archives" "content_providers" "plugins" "collections")
   foreach f (  \
      $base_url/$cls/new \
      $base_url/$cls/mine  \
      $base_url/$cls/noaction  \
      $base_url/$cls/1/edit  \
      $base_url/$cls/1/status  \
      $base_url/$cls/1/noaction  \
   )
      wget -S -O /dev/null $f  >& stderr
      echo -n $f; fgrep HTTP stderr | fgrep -v awaiting
   end
end
 
echo "\n>>>> archives";
echo ">> EXPECT OK ";
foreach ar ("3" "find/SDC")
   foreach act (  \
              "show/state/active" \
              "archival_units" \
              "archival_units.xml" \
              "archival_units" \
              "archival_units/austates/test,retest" \
              "archival_units/austates/test,retest.xml"  \
              )
	   set f = "$base_url/archives/$ar/$act";
	   wget -S -O /dev/null $f  >& stderr
	   echo -n $f; fgrep HTTP stderr | fgrep -v awaiting
   end
end

echo ">> EXPECT Not Acceptable ";
foreach ar ("3" "find/SDC" )
   foreach act ( "plugins.xml" )
      set f = "$base_url/archives/$ar/$act";
      wget -S -O /dev/null $f  >& stderr
      echo -n $f; fgrep HTTP stderr | fgrep -v awaiting
   end 
end 

echo ">> EXPECT ERROR ";
foreach ar ("3" "find/EML" "find/SDC")
   foreach act ( "status" )
      set f = "$base_url/archives/$ar/$act";
      wget -S -O /dev/null $f  >& stderr
      echo -n $f; fgrep HTTP stderr | fgrep -v awaiting
   end
end

echo "\n>>>> content_providers";
echo ">> EXPECT OK ";
foreach obj ("3" "find/vt" "find/ma")
   foreach act ( \
              "show/state/retired" \
              "archival_units" \
              "archival_units.xml" \
              "archival_units/austates/test,retest" \
              "archival_units/austates/test,retest.xml" \
              "plugins"  \
              "plugins/state/active"  \
              "plugins.xml"  \
   )
      set f = "$base_url/content_providers/$obj/$act";
      wget -S -O /dev/null $f  >& stderr
      echo -n $f; fgrep HTTP stderr | fgrep -v awaiting
   end
end
echo ">> EXPECT ERROR ";
foreach obj ("3" "find/vt" "find/ma")
   foreach act ( "status" \
   )
      set f = "$base_url/content_providers/$obj/$act";
      wget -S -O /dev/null $f  >& stderr
      echo -n $f; fgrep HTTP stderr | fgrep -v awaiting
   end
end

echo "\n>>>> collections";
echo ">> EXPECT OK ";
foreach act ( "all_or_mine" "index")
   foreach params ( "state/active" "")
      set f = "$base_url/collections/$act/$params" 
      wget -S -O /dev/null $f  >& stderr
      echo -n $f; fgrep HTTP stderr | fgrep -v awaiting
   end
end
set  act =  "index"
foreach state ("all" "active" "retired") 
   foreach format ("" ".xml" ) 
      set f =  "$base_url/collections/$act/state/$state$format"
      wget -S -O /dev/null $f >& stderr
      echo -n $f; fgrep HTTP stderr | fgrep -v awaiting
   end
end
foreach obj ( "1" "find/Aardvark" "find/Auburn_University_Treasure_Maps")
   foreach act ( "show" \
                 "show.xml" \
                )
      set f =  "$base_url/collections/$obj/$act"
      wget -S -O /dev/null $f >& stderr
      echo -n $f; fgrep HTTP stderr | fgrep -v awaiting
   end
end
echo ">> EXPECT ERROR ";
foreach obj ( "1" "find/Aardvark" "find/Auburn_University_Treasure_Maps")
   foreach act ( "manage_aus_by_state" )
      set f = "$base_url/collections/$obj/$act";
      wget -S -O /dev/null $f >& stderr
      echo -n $f; fgrep HTTP stderr | fgrep -v awaiting
   end
end


echo "\n>>>> plugins";
echo ">> EXPECT OK ";
foreach act ( "all_or_mine" "index")
   foreach f  ( \
         "$base_url/plugins/$act" \
         "$base_url/plugins/$act/state/retired" \
            )
      wget -S -O /dev/null $f  >& stderr
      echo -n $f; fgrep HTTP stderr | fgrep -v awaiting
   end
end

foreach obj ( "1" "find/edu|vt|library|generic" )
   foreach act ( \
              "show" \
              "archival_units" \
              "archival_units.xml" \
              "archival_units/austates/test,retest" \
              "archival_units/austates/test,retest.xml")
      set f = "$base_url/plugins/$obj/$act";
      wget -S -O /dev/null $f >& stderr
      echo -n $f; fgrep HTTP stderr | fgrep -v awaiting
   end
end

echo "\n>>>> archival_units";
echo ">> EXPECT OK ";
foreach act (\
              "archival_units/austates/test,retest" \
              "archival_units/austates/test,retest.xml" \
              "archival_units/austates/preserved,retest.xml" \
           )
      set f = "$base_url/$act"; 
      wget -S -O /dev/null $f  >& stderr
      echo -n $f; fgrep HTTP stderr | fgrep -v awaiting
end
echo ">> EXPECT ERROR"; 
foreach act (\
              "archival_units/index.xml" \
            ) 
      set f = "$base_url/$act"; 
      wget -S -O /dev/null $f  >& stderr
      echo -n $f; fgrep HTTP stderr | fgrep -v awaiting
end
