#!/bin/tcsh  -e
if ($?RAILSROOT) then 
	cd $RAILS_ROOT; 
endif
pwd 

if ($1 == "start") then 
	echo "starting maintenance"; 
	cp public/system/maintenance.html  public/system/down_for_maintenance.html
	exit 0; 
endif
if ($1 == "stop") then 
	echo "ending maintenance"; 
	rm   public/system/down_for_maintenance.html
	exit 0; 
endif 
if (-f  public/system/down_for_maintenance.html) then 
	echo "in mantenance"; 
else 
	echo "up and running"; 
endif 
