#!/usr/bin/perl  

use Getopt::Long; 
$PAGE;
$DOTRACE = 1; 

if (0 == parseargs()) {
    doit(); 
    exit(0); 
}
exit(1) ;

sub parseargs 
{
 $result = GetOptions( 
            "help" => \$HELP,
            "t" => \$DOTRACE 
           ); 
  if ($result == 1) { 
     $PAGE = shift(@ARGV); 
     if ($HELP || !$PAGE) { 
        return usage(); 
     }
  } else {
     return usage(); 
  }
}
 
sub usage 
{
print   "usage: valManifest [OPT} url \n"; 
print "\t-help: print this help message\n";
print "\t-t: whether to trace the script's actions\n"; 
print "\n"; 
print "get url and test whether it contains the requited LOCKSS menifest verbiage\n";  
}

sub doit
{
   $cmd = "wget -O - $PAGE | fgrep 'LOCKSS system has permission to collect, preserve, and serve this Archival Unit'"; 
   my($rc) = systm($cmd);
   if ($rc == 0) {
         print "IS MANIFEST\n"; 
   }  else { 
         print "IS NOT MANIFEST\n"; 
   }
}

sub systm
{
   my $cmd = join(' ', @_); 
   trace($cmd); 
   my($rc) = system($cmd); 
   return $rc; 
}

sub trace
{
   my $str = join(' ', @_); 
   print $str . "\n"; 
}


