#!/bin/tcsh 
echo "----------------------------------"
echo "- $0 "
echo "----------------------------------"
set usr = lockssview
set pwd = XXX
foreach t (status_locksscache \
	status_locksscacheauid      \
	status_locksscacheausummary \
	status_locksscrawlstatus    \
	status_masterauid           \
	status_url                  \
	status_urlreport  ) 
	echo "OPTIMIZE TABLE  $t" | mysql -u $usr --password=$pwd lockssview  > /dev/null 
end 

mysqlshow --status lockssview -u $usr --password=$pwd 'status%' 

