#!/bin/tcsh 
source ~/.metaarchive.rc 

foreach f (CrawlStatus  CrawlStatus.noerrors  Status  Status.crawling  Status.sizes) 
  cat $DATE/*/$f > $DATE/$f 
end 
cat $DATE/Status.sizes 
cat $DATE/CrawlStatus.noerrors
cat $DATE/Status.crawling

